# Generated by Django 4.0.8 on 2022-11-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_evalutaion_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.BooleanField(default=False)),
                ('workExperience', models.BooleanField(default=False)),
                ('city', models.BooleanField(default=False)),
                ('rollNo', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('gradYear', models.BooleanField(default=False)),
                ('cgpa', models.BooleanField(default=False)),
                ('gpa', models.BooleanField(default=False)),
                ('collegeName', models.BooleanField(default=False)),
                ('contactNo', models.BooleanField(default=False)),
                ('contactRec', models.BooleanField(default=False)),
                ('stream', models.BooleanField(default=False)),
                ('branch', models.BooleanField(default=False)),
                ('major', models.BooleanField(default=False)),
                ('degree', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('jobRole', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('disclaimer', models.CharField(default='I agree not to copy code from any source(including websites, books or friends and colleagues) to complete this assessment. I may, however, reference programming language documentation or use an IDE that has code completion features', max_length=5000)),
                ('disclaimerCheck', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.assessment')),
            ],
        ),
    ]
