# Generated by Django 4.0.8 on 2022-11-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_candidatedetails_candidatedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetail',
            name='branch',
        ),
    ]
