# Generated by Django 4.0.8 on 2022-11-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='isAttempted',
            field=models.BooleanField(default=False),
        ),
    ]
