# Generated by Django 4.0.8 on 2022-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_invitation_isattempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='section',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='link',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
