# Generated by Django 4.0.8 on 2022-11-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Section', max_length=1024),
        ),
    ]
