# Generated by Django 4.0.8 on 2022-11-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.section'),
        ),
    ]
