# Generated by Django 4.0.8 on 2022-11-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptInformation', models.CharField(default='', max_length=1000000)),
                ('marks', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.section')),
                ('testReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testreport')),
            ],
        ),
    ]
