# Generated by Django 4.0.8 on 2022-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_assessment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='multiChoice',
            field=models.BooleanField(default=False),
        ),
    ]
