# Generated by Django 4.0.8 on 2022-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_optionset_optionstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
